name: 'Check PR Description'
description: 'Checks that the body or the added code contains a word'
inputs:
  github-token:
    description: 'Github token, added magically'
  bodyContains:
    description: 'Word that must be contained in the PR body, can be left blank'
runs:
  using: 'node12'
  main: 'index.js'
